In [1]:
import control
import numpy as np

num = [2,1,1,2]
den = [1,4,5,2]
sys = control.tf(num,den)
print control.tf2ss(sys)

A = [[-4. -5. -2.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]]

B = [[ 1.]
 [ 0.]
 [ 0.]]

C = [[-7. -9. -2.]]

D = [[ 2.]]



In [4]:
num = [2,1,1,2]
den = [1,4,5,2]
sys = control.tf2ss(num,den)
print (sys)

A = [[-4. -5. -2.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]]

B = [[ 1.]
 [ 0.]
 [ 0.]]

C = [[-7. -9. -2.]]

D = [[ 2.]]

